
import Head from 'next/head'

import { useDispatch } from 'react-redux';
import { onDeviceDetected, onLoadData } from '../store/data/appSlice';
import fetch from 'isomorphic-fetch'
import { useLanguage } from '../hooks/useLanguage';
import { NavBar } from '../components/NavBar';
import { Footer } from '../components/Footer';
import { PreFooter } from '../components/PreFooter';
import { Header } from '../components/Header';
import { HeaderMovil } from '../components/movil/HeaderMovil';
import { Legals } from '../components/Legals';
import { Promotions } from '../components/Promotions';
import { CarouselComponent } from '../components/CarouselComponent';
import { useDeviceDetected } from '../hooks/useDeviceDetected';



const Home = (props) => {
  const {movil } = useDeviceDetected();
  const { locale } = useLanguage();

  const dispatch = useDispatch();

  switch (locale) {
    case 'en':
      dispatch(onLoadData(props.data.en))
      break;
    case 'es':
      dispatch(onLoadData(props.data.es))
      break;
    default:
      dispatch(onLoadData(props.data.es))
      break;
  }

  if (movil) {
    dispatch(onDeviceDetected('isMobile'))
  } else {
    dispatch(onDeviceDetected('isBrowser'))
  }

  return (
    <div >
      <Head>
        <title>Xcaret</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      {
        (movil) ? <HeaderMovil /> : <Header />
      }
      <Promotions />
      <CarouselComponent />
      <Legals />
      <PreFooter />
      <Footer />

    </div>
  )
}

Home.getInitialProps = async (ctx) => {
  const res = await fetch('https://raw.githubusercontent.com/javialcocer/test-json/main/data.json');
  const resJSON = await res.json();

  return { data: resJSON }
}


export default Home